/**
 * Maps IATA airport codes to their city names.
 * Keys are uppercase 3-letter IATA codes.
 */
export const AIRPORT_CITIES: Record<string, string> = {
  // United States
  ATL: 'Atlanta',
  AUS: 'Austin',
  BNA: 'Nashville',
  BOS: 'Boston',
  BUF: 'Buffalo',
  BWI: 'Baltimore',
  CLE: 'Cleveland',
  CLT: 'Charlotte',
  CMH: 'Columbus',
  DAL: 'Dallas',
  DCA: 'Washington D.C.',
  DEN: 'Denver',
  DFW: 'Dallas',
  DTW: 'Detroit',
  EWR: 'Newark',
  FLL: 'Fort Lauderdale',
  HNL: 'Honolulu',
  HOU: 'Houston',
  IAD: 'Washington D.C.',
  IAH: 'Houston',
  IND: 'Indianapolis',
  JAX: 'Jacksonville',
  JFK: 'New York City',
  LAS: 'Las Vegas',
  LAX: 'Los Angeles',
  LGA: 'New York City',
  MCI: 'Kansas City',
  MCO: 'Orlando',
  MDW: 'Chicago',
  MEM: 'Memphis',
  MIA: 'Miami',
  MKE: 'Milwaukee',
  MSP: 'Minneapolis',
  MSY: 'New Orleans',
  OAK: 'Oakland',
  OGG: 'Maui',
  ORD: 'Chicago',
  PDX: 'Portland',
  PHL: 'Philadelphia',
  PHX: 'Phoenix',
  PIT: 'Pittsburgh',
  RDU: 'Raleigh',
  RSW: 'Fort Myers',
  SAN: 'San Diego',
  SAT: 'San Antonio',
  SEA: 'Seattle',
  SFO: 'San Francisco',
  SJC: 'San Jose',
  SJU: 'San Juan',
  SLC: 'Salt Lake City',
  SMF: 'Sacramento',
  STL: 'St. Louis',
  TPA: 'Tampa',
  TUL: 'Tulsa',
  // US - Alaska
  ANC: 'Anchorage',
  FAI: 'Fairbanks',
  JNU: 'Juneau',
  KTN: 'Ketchikan',
  SIT: 'Sitka',
  // US - Hawaii
  KOA: 'Kona',
  LIH: 'Lihue',
  // US - Additional
  AVL: 'Asheville',
  BDL: 'Hartford',
  RNO: 'Reno',
  // Canada
  YEG: 'Edmonton',
  YOW: 'Ottawa',
  YUL: 'Montreal',
  YVR: 'Vancouver',
  YYC: 'Calgary',
  YYZ: 'Toronto',
  YHZ: 'Halifax',
  YQB: 'Quebec City',
  YYJ: 'Victoria',
  YVE: 'Vancouver East',
  YWG: 'Winnipeg',
  YLW: 'Kelowna',
  // Europe
  AMS: 'Amsterdam',
  ARN: 'Stockholm',
  ATH: 'Athens',
  BCN: 'Barcelona',
  BER: 'Berlin',
  BRU: 'Brussels',
  CDG: 'Paris',
  CPH: 'Copenhagen',
  DUB: 'Dublin',
  DUS: 'Düsseldorf',
  FCO: 'Rome',
  FRA: 'Frankfurt',
  GVA: 'Geneva',
  HAM: 'Hamburg',
  HEL: 'Helsinki',
  IST: 'Istanbul',
  LHR: 'London',
  LGW: 'London',
  LIS: 'Lisbon',
  MAD: 'Madrid',
  MAN: 'Manchester',
  MUC: 'Munich',
  NCE: 'Nice',
  OSL: 'Oslo',
  ORY: 'Paris',
  PRG: 'Prague',
  STN: 'London',
  VCE: 'Venice',
  VIE: 'Vienna',
  WAW: 'Warsaw',
  ZRH: 'Zurich',
  // Asia-Pacific
  BKK: 'Bangkok',
  CAN: 'Guangzhou',
  CGK: 'Jakarta',
  CNX: 'Chiang Mai',
  DEL: 'Delhi',
  DXB: 'Dubai',
  HKG: 'Hong Kong',
  ICN: 'Seoul',
  KIX: 'Osaka',
  KUL: 'Kuala Lumpur',
  MEL: 'Melbourne',
  MNL: 'Manila',
  NRT: 'Tokyo',
  HND: 'Tokyo',
  PEK: 'Beijing',
  PKX: 'Beijing',
  PVG: 'Shanghai',
  SHA: 'Shanghai',
  SIN: 'Singapore',
  SYD: 'Sydney',
  TPE: 'Taipei',
  // Latin America & Caribbean
  BOG: 'Bogotá',
  GRU: 'São Paulo',
  GIG: 'Rio de Janeiro',
  LIM: 'Lima',
  MEX: 'Mexico City',
  SCL: 'Santiago',
  // Mexico - Additional
  CUN: 'Cancun',
  CZL: 'Cozumel',
  PVR: 'Puerto Vallarta',
  SJD: 'Los Cabos',
  ZIH: 'Zihuatanejo',
  MZT: 'Mazatlan',
  // Caribbean
  AUA: 'Aruba',
  BGI: 'Barbados',
  BDA: 'Bermuda',
  BZE: 'Belize City',
  CUR: 'Curaçao',
  KIN: 'Kingston',
  MBJ: 'Montego Bay',
  NAS: 'Nassau',
  PTY: 'Panama City',
  PUJ: 'Punta Cana',
  SXM: 'St. Maarten',
  SKB: 'St. Kitts',
  LIL: 'St. Lucia',
  TCI: 'Turks and Caicos',
  VCT: 'St. Vincent',
  TRT: 'Tobago',
  // Africa & Middle East
  CAI: 'Cairo',
  CPT: 'Cape Town',
  DOH: 'Doha',
  JNB: 'Johannesburg',
  NBO: 'Nairobi',
};

/**
 * Returns the city name for the given IATA airport code, or undefined if not found.
 */
export function getCityFromAirportCode(code: string): string | undefined {
  return AIRPORT_CITIES[code.trim().toUpperCase()];
}
